name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20
          cache: npm
      - name: Install circom
        run: |
          curl -sSL https://github.com/iden3/circom/releases/download/v2.2.3/circom-linux-amd64 -o /usr/local/bin/circom
          chmod +x /usr/local/bin/circom
      - run: npm ci
      - run: npm test
